export const SELECT_FOLDER = "SELECT_FOLDER";
export const UPDATE_FOLDER = "UPDATE_FOLDER";
export const SET_CHILDFOLDER = "SET_CHILDFOLDER";
export const SET_CHILDFILE = "SET_CHILDFILE";
export const SET_USER = "SET_USER";
